

compiler:
  output_dir: "exec"
  g++: "g++-10"
  args: ["-std=c++17", "-O3"]

temp_dir: ".temp"
problem_config_file: "problem.yaml"

generation:
  tests_dir: "tests"
  run_deterministic_check: No 
  num_workers: 4

evaluation:
  timeout_multiplier: 3.0          # Execution timeout (TL multiplier) 
  tl_close_range: [0.75, 1.25]     # Range to display close to tl warnings (TL multipliers)

discovery:
  patterns:
  - pattern: "gen*.cpp"
    kind: generator
  - pattern: "valid*.cpp"
    kind: validator
  - pattern: "sol*.cpp"
    kind: solution
  - pattern: "tests.sh"
    kind: tests

