#!/usr/bin/env python3

from commands import runall, create, eval, generate, clean
from lib.base import ProblemCfg
import argparse
import os 
import yaml
from colorama import Fore 


def parse_args():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(help='commands')
    
    for command_module in [runall, create, eval, generate, clean]:
        name = command_module.__name__.split('.')[-1]
        subparser = subparsers.add_parser(
            name, parents=[command_module.parser])
        subparser.set_defaults(
            run=command_module.run, 
            command=name)

    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    config_path = os.path.join(os.path.dirname(__file__), "config.yaml")
    with open(config_path, 'r') as f:
        cfg = yaml.load(f, Loader=yaml.FullLoader)
        # cfg['base_dir'] = '' # os.path.relpath('.')
    if os.path.exists(cfg['problem_config_file']):
        with open(cfg['problem_config_file']) as f:
            cfg['problem'] = ProblemCfg(**yaml.load(f, Loader=yaml.FullLoader))
    elif args.command != 'create':
        print(f"{Fore.RED}ERROR: You don't seem to be inside a problem directory ")
        print(f"  (file '{cfg['problem_config_file']}' not found){Fore.RESET}")
        exit(-1)
    args.run(cfg, args)